baseURL = "www.open-dc.com"
languageCode = "en-uk"
title = "OpenDC Ltd"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
math = true
theme = "hero"

[params]
	AuthorName = "Daniel Marin"
    google_analytics_id=""	

#################################################################
# LANGUAGES
#################################################################	
[languages]
	# English -----------------------------------------------------
	[languages.en]
		languageName = "En"
		weight = 1    
		languageCode = "en-uk"
		contentDir = "content/en"
		url = "/en/"
		title = "Doc List" #"OpenDC UK" #???
		home = "home"
		# logo = "Dot"
		
		# Navigation
		[Languages.en.menu]
			# Services
    		[[Languages.en.menu.main]]
			weight = 1
			name = "services"
			url = "/services/"
			# Work
    		[[Languages.en.menu.main]]
			weight = 2
			name = "work"
			url = "/work/"
			# About
			[[Languages.en.menu.main]]
			weight = 3
			name = "about"
			url = "/about/"
			# Contact
			[[Languages.en.menu.main]]
			weight = 4
			name = "contact"
			url = "/contact/"
			# Language ****************
			# [[Languages.en.menu.main]]
			# weight = 5
			# name = "language"
			# identifier = "lang"
			# url = "/en/about/"
			# hasChildren = true
				##English
				# [[Languages.en.menu.main]]
				# parent = "lang"
				# name = "En"
				# URL = "/en/about/"
				# weight = 1
				##French
				# [[Languages.en.menu.main]]
				# parent = "lang"
				# name = "Fr"
				# URL = "/fr/about/"
				# weight = 2
			[[Languages.en.menu.main]]
			weight = 5
			name = "En"
			url = "/en/"
			[[Languages.en.menu.main]]
			weight = 6
			name = "Fr"
			url = "/fr/"
				
	# French -----------------------------------------------------
	[languages.fr]
		languageName = "Fr"
		weight = 1    
		languageCode = "fr"
		contentDir = "content/fr"
		url = "/fr/"
		title = "Doc List" #"OpenDC UK" #???
		home = "services"
		# logo = "Dot"
		
		# Navigation
		[Languages.fr.menu]
			# Services
    		[[Languages.fr.menu.main]]
			weight = 1
			name = "services"
			url = "/services/"
			# Work
    		[[Languages.fr.menu.main]]
			weight = 2
			name = "work"
			url = "/work/"
			# About
			[[Languages.fr.menu.main]]
			weight = 3
			name = "about"
			url = "/about/"
			# Contact
			[[Languages.fr.menu.main]]
			weight = 4
			name = "contact"
			url = "/contact/"
			# Language ****************
			# [[Languages.en.menu.main]]
			# weight = 5
			# name = "language"
			# identifier = "lang"
			# url = "/fr/about/"
			# hasChildren = true
				##English
				# [[Languages.fr.menu.main]]
				# parent = "lang"
				# name = "En"
				# URL = "/en/about/"
				# weight = 1
				##French
				# [[Languages.fr.menu.main]]
				# parent = "lang"
				# name = "Fr"
				# URL = "/fr/about/"
				# weight = 2
			[[Languages.fr.menu.main]]
			weight = 5
			name = "En"
			url = "/en/"
			[[Languages.fr.menu.main]]
			weight = 6
			name = "Fr"
			url = "/fr/"
	# Portuguese
	# [languages.pt]
		# languageName = "Pt"
		# contentDir = "content/portuguese"
		# title = "OpenDC Portugal"
		# weight = 3

# disableLanguages = ["pt"]    