########################################################################
## LOCALHOST
baseURL =  "./" # localhost
relativeURLs = true

## FILE SYSTEM
# baseURL =  "c:/Users/dmarin/Dropbox/Pro/info/Git/Project_repositories/opendc_website/open-dc/public/" # "File system
# relativeURLs = false

## WEB
# baseURL =  "www.open-dc.com"	# Web
# relativeURLs = false
########################################################################

languageCode = "en-uk"
title = "OpenDC Ltd"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
math = true
theme = "airspace"

[permalinks]
   services = "services/:title/"
   work = "work/:title/"
   about = "about/:title/"
   contact = "contact/:title/"

  #----------------------------------------------
 [Languages]
	# English -----------------------------------------------------
	[Languages.en]
		languageName = "En"
		weight = 1    
		languageCode = "en-uk"
		url = "/index.html" # # url = "/"
		title = "OpenDC Ltd - UK" #"OpenDC UK" #???
		home = "Home"
		# logo = "images/flag_uk.png"
		
		# Navigation
		[Languages.en.menu]
			# Services
    		[[Languages.en.menu.header]]
			weight = 2
			name = "Services"
			url = "/services/index.html" #url = "/services"
			# Work
    		[[Languages.en.menu.header]]
			weight = 3
			name = "Work"
			url = "/work/index.html" # url = "/work"
			# About
			[[Languages.en.menu.header]]
			weight = 4
			name = "About"
			url = "/about/index.html" # url = "/about"
			# Contact
			[[Languages.en.menu.header]]
			weight = 5
			name = "Contact"
			url = "/contact/index.html" # url = "/contact" #
			# En
			[[Languages.en.menu.header]]
			weight = 6
			name = "En"
			url = "/index.html"
			# Fr
			[[Languages.en.menu.header]]
			weight = 7
			name = "Fr"
			url = "/fr/index.html"
			#------------------------------------------
			## Footer
			#------------------------------------------
			[[Languages.en.menu.footer]]
			weight = 1
			name = "Home"
			url = "/index.html"
			[[Languages.en.menu.footer]]
			weight = 2
			name = "About us"
			url = "/about/index.html"
			[[Languages.en.menu.footer]]
			weight = 3
			name = "Contact us"
			url = "/contact/index.html"
			[[Languages.en.menu.footer]]
			weight = 4
			name = "En"
			url = "/index.html"
			# Fr
			[[Languages.en.menu.footer]]
			weight = 5
			name = "Fr"
			# url = "/index.html" # Changed as all translations are managed in html files via i18n
			url = "/fr/index.html"
	
	# French -----------------------------------------------------
	[Languages.fr]
		languageName = "Fr"
		weight = 1    
		languageCode = "fr-fr"
		url = "/index.html" ## url = "/fr"
		# url = "/fr/index.html" ## url = "/fr"
		title = "OpenDC Ltd - Fr" #"OpenDC UK" #???
		home = "Home"
		# Navigation
		[Languages.fr.menu]
			# Services
    		[[Languages.fr.menu.header]]
			weight = 2
			name = "Services"
			url = "/fr/services/index.html" #url = "/fr/services"
			# Work
    		[[Languages.fr.menu.header]]
			weight = 3
			name = "Projets"
			url = "/fr/work/index.html" #url = "/fr/work"
			# About
			[[Languages.fr.menu.header]]
			weight = 4
			name = "A-propos"
			url = "/fr/about/index.html" #url = "/fr/about"
			# Contact
			[[Languages.fr.menu.header]]
			weight = 5
			name = "Contact"
			url = "/fr/contact/index.html" #url = "/fr/contact"
			[[Languages.fr.menu.header]]
			## English
			weight = 6
			name = "En"
			url = "/index.html" #url = "/"
			## French
			[[Languages.fr.menu.header]]
			weight = 7
			name = "Fr"
			url = "/fr/index.html" # Changed as all translations are managed in html files via i18n
			# ------------------------------------------
			# Footer
			# ------------------------------------------
			[[Languages.fr.menu.footer]]
			weight = 1
			name = "Accueil"
			url = "/fr/index.html"
			[[Languages.fr.menu.footer]]
			weight = 2
			name = "À propos"
			url = "/fr/about/index.html"
			[[Languages.fr.menu.footer]]
			weight = 3
			name = "Contact"
			url = "/fr/contact/index.html"
			## English
			[[Languages.fr.menu.footer]]
			weight = 4
			name = "En"
			url = "/fr/index.html"
			## French
			[[Languages.fr.menu.footer]]
			weight = 5
			name = "Fr"
			url = "/index.html"
#----------------------------------------------

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260
	
	AuthorName = "Daniel Marin"
	google_analytics_id = "UA-132053500-1"	
	copyright = "Copyright - Website created by OpenDC Ltd with Hugo static site generator	 and Theme Developed by Themefisher. All rights reserved."
	logo = "/img/logo_opendc_blue_plain_svg.svg"
	headerFontSize = "4"	# does not work

	dateFormat = "6 January 2006"

	home = "Home"
	
	# Home page intro
  [params.slider]
    enable = true
    # title = "OpenDC - Open Data Consultants" # Defined in partials/slider.html
	# subtitle = "We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"

	# Home page section About us
  [params.wrapper]
    enable = true
    # title = "About Us" # Defined in partials/wrapper.html
    # italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
    # paragraph = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id"

	# Desactivated
  [params.blog]
    enable = false #true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

	# Home page section Work
  [params.feature]
    enable = true
    # title = "Our work" # Defined in partials/feature.html
    # content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [params.feature.button]
      # caption = "View Works" # Defined in partials/feature.html
      url = "/work/index.html"
	  
  # [params.services] #==> Defined in data/service.yml
	# enable = true
	## Services titles defined in i18n/en.toml and fr.toml
	# logo_service_01 = "/img/services/s01.png"	#_icon_gps
	# logo_service_02 = "/img/services/s02.png" 	#_icon_gsm
	# logo_service_03 = "/img/services/s03.png"	#_icon_stats_ci
	# logo_service_04 = "/img/services/s04.png"	#_icon_process
	# logo_service_05 = "/img/services/s05.png"	#_icon_qgis
	# logo_service_06 = "/img/services/s06.png"	#_icon_map_world
	# [params.services.button]
      # url = "/services/index.html"
	
	# Desactivated
  [params.call]
    enable = false # true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

	
	# Desactivated
  [params.contact]
    enable = false #true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
