baseURL = "www.open-dc.com"
languageCode = "en-uk"
title = "OpenDC v0.2"
theme = "hero"

[params]
    google_analytics_id=""

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
	
[languages]
  [languages.en]
    contentDir = "content/english"
	title = "OpenDC UK"
    weight = 1    
  [languages.fr]
	contentDir = "content/french"
    title = "OpenDC France"
    weight = 2
  [languages.pt]
	contentDir = "content/portuguese"
    title = "OpenDC Portugal"
    weight = 3

disableLanguages = ["pt"]    